//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleLoginData
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleLoginData { }
#else

	public class SampleLoginData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleLoginData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Awful;component/SampleData/SampleLoginData/SampleLoginData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private string _StatusMessage = string.Empty;

		public string StatusMessage
		{
			get
			{
				return this._StatusMessage;
			}

			set
			{
				if (this._StatusMessage != value)
				{
					this._StatusMessage = value;
					this.OnPropertyChanged("StatusMessage");
				}
			}
		}

		private bool _IsLoading = false;

		public bool IsLoading
		{
			get
			{
				return this._IsLoading;
			}

			set
			{
				if (this._IsLoading != value)
				{
					this._IsLoading = value;
					this.OnPropertyChanged("IsLoading");
				}
			}
		}
	}
#endif
}
