//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Awful.Core.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Awful.Core.Test.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples/sampleEditFolder.txt.
        /// </summary>
        internal static string sample_editfolder {
            get {
                return ResourceManager.GetString("sample_editfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples/sampleForumPage.txt.
        /// </summary>
        internal static string sample_forumPage {
            get {
                return ResourceManager.GetString("sample_forumPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples/samplePM.txt.
        /// </summary>
        internal static string sample_privatemessage {
            get {
                return ResourceManager.GetString("sample_privatemessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples/samplePMFolder.txt.
        /// </summary>
        internal static string sample_privatemessagefolder {
            get {
                return ResourceManager.GetString("sample_privatemessagefolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples/samplePMForm.txt.
        /// </summary>
        internal static string sample_privatemessageform {
            get {
                return ResourceManager.GetString("sample_privatemessageform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples/sampleThreadNode.txt.
        /// </summary>
        internal static string sample_threadnode {
            get {
                return ResourceManager.GetString("sample_threadnode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples/sampleThreadPage.txt.
        /// </summary>
        internal static string sample_threadpage {
            get {
                return ResourceManager.GetString("sample_threadpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples/sampleThreadPagePost.txt.
        /// </summary>
        internal static string sample_threadPagePost {
            get {
                return ResourceManager.GetString("sample_threadPagePost", resourceCulture);
            }
        }
    }
}
